labs/Server_Side/MVC/Day_7-8/Institute/Controllers/DepartmentController.cs
using Institute.Models;
using Institute.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Institute.Controllers
{
    public partial class DepartmentController : Controller
    {
        private readonly InstituteContext context = new();
        public IActionResult Index(int page = 1)
        {
            int pageSize = 5;
            var departmentVM = new PaginationVM<Department>()
            {
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling((double)context.Departments.Count() / pageSize),
                Items = context.Departments.Skip((page - 1) * pageSize).Take(pageSize).ToList()
            };

            return View("Index", departmentVM);
        }

        [HttpPost]
        public IActionResult Search(string searchString, string propertyToSearch)
        {
            List<Department> filteredDepartments;
            SearchVM<Department> departmentSearchVM;

            switch (propertyToSearch)
            {
                case "manager":
                    filteredDepartments = context.Departments.Where(dept => dept.Manager.Contains(searchString)).ToList();
                    break;
                default: // Otherwise, search by name.
                    filteredDepartments = context.Departments.Where(dept => dept.Name.Contains(searchString)).ToList();
                    break;
            }

            departmentSearchVM = new SearchVM<Department>()
            {
                SearchString = searchString,
                SearchProperty = propertyToSearch,
                Items = filteredDepartments
            };

            return View("Search", departmentSearchVM);
        }

        public IActionResult Details(int id)
        {
            var departmentVM = context.Departments.Where(tr => tr.Id == id)
                .Select(dept => new DepartmentDetailsVM
                {
                    DepartmentId = dept.Id,
                    DepartmentName = dept.Name,
                    DepartmentManager = dept.Manager,
                    Instructors = dept.Instructors.ToList(),
                    Courses = dept.Courses.ToList()
                }
                ).FirstOrDefault();

            return View("Details", departmentVM);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var addDepartmentVM = new DepartmenModifytVM();

            return View("Add", addDepartmentVM);
        }

        [HttpPost]
        public IActionResult Add(DepartmenModifytVM departmentVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", departmentVM);
            }

            var department = new Department()
            {
                Name = departmentVM.DepartmentName,
                Manager = departmentVM.DepartmentManager
            };

            context.Departments.Add(department);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var department = context.Departments.Find(id);

            var editDepartmentVM = new DepartmenModifytVM()
            {
                DepartmentId = department.Id,
                DepartmentName = department.Name,
                DepartmentManager = department.Manager
            };

            return View("Edit", editDepartmentVM);
        }

        [HttpPost]
        public IActionResult Edit(DepartmenModifytVM editDepartmentVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", editDepartmentVM);
            }

            var department = context.Departments.Find(editDepartmentVM.DepartmentId);

            department.Name = editDepartmentVM.DepartmentName;
            department.Manager = editDepartmentVM.DepartmentManager;

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            try
            {
                var department = context.Departments.Find(id);
                if (department == null)
                {
                    return StatusCode(404, new { message = "Department not found." });
                }
                context.Departments.Remove(department);
                context.SaveChanges();
                return StatusCode(201, new { message = "Department successfully removed." });
            }
            catch
            {
                return StatusCode(500, $"An error occured while removing the Department.");
            }
        }
    }
}

labs/Server_Side/MVC/Day_7-8/Institute/Controllers/TraineeController.cs
using Institute.Models;
using Institute.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Institute.Controllers
{
    public class TraineeController : Controller
    {
        private readonly InstituteContext context = new();
        private readonly IWebHostEnvironment webHostEnv;

        public TraineeController(IWebHostEnvironment webHostEnvironment)
        {
            webHostEnv = webHostEnvironment;
        }

        public IActionResult ShowResult(int id, int crsid)
        {
            StudentWithCourseDegreeVM stdCrsVM;
            var traineeWithCourse = context.CourseResults
                .Where(crs => crs.TraineeId == id && crs.CourseId == crsid)
                .Select
                (
                    crsresult => new
                    {
                        CrsName = crsresult.Course.Name,
                        TraineeName = crsresult.Trainee.Name,
                        crsresult.Degree,
                        IsPassed = crsresult.Degree >= crsresult.Course.MinDegree
                    }
                ).FirstOrDefault();

            if (traineeWithCourse == null)
            {
                return NotFound();
            }

            stdCrsVM = new StudentWithCourseDegreeVM()
            {
                CrsName = traineeWithCourse.CrsName,
                TraineeName = traineeWithCourse.TraineeName,
                Degree = traineeWithCourse.Degree,
                IsPassed = traineeWithCourse.IsPassed
            };

            return View("ShowResult", stdCrsVM);
        }

        public IActionResult ShowTraineeResult(int id)
        {
            var courseResults = context.CourseResults
                .Where(crs => crs.TraineeId == id)
                .Select
                (
                    crsresult => new StudentWithCourseDegreeVM()
                    {
                        CrsName = crsresult.Course.Name,
                        Degree = crsresult.Degree,
                        IsPassed = crsresult.Degree >= crsresult.Course.MinDegree
                    }
                ).ToList();

            if (courseResults.Count == 0)
            {
                return NotFound();
            }

            var traineeResultsVM = new TraineeResults()
            {
                TraineeName = context.Trainees.Find(id).Name,
                CourseResults = courseResults
            };

            return View("ShowTraineeResult", traineeResultsVM);
        }

        public IActionResult Login(int id)
        {
            var cookieOptions = new CookieOptions()
            {
                Expires = System.DateTime.Now.AddDays(2)
            };

            Response.Cookies.Append("TraineeId", id.ToString(), cookieOptions);

            HttpContext.Session.SetString("TraineeId", id.ToString());


            return Content("Logged in successfully");
        }

        public IActionResult CheckLogin()
        {
            string traineeId = Request.Cookies["TraineeId"];

            if (string.IsNullOrEmpty(traineeId))
            {
                return Content("Not logged in");
            }

            var trainee = context.Trainees.Find(int.Parse(traineeId));
            if (trainee == null)
            {
                return Content("Not logged in");
            }

            string sessionTraineeId = HttpContext.Session.GetString("TraineeId");

            if (string.IsNullOrEmpty(sessionTraineeId))
            {
                return Content("Not logged in");
            }

            var traineeUsingSession = context.Trainees.Find(int.Parse(sessionTraineeId));

            return Content($"Trainee: {trainee.Name} Logged in successfully\n" +
                $"Trainee Name using session {traineeUsingSession.Name}");
        }

        public IActionResult Index(int page = 1)
        {
            int pageSize = 5;
            var traineeVM = new PaginationVM<Trainee>()
            {
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling((double)context.Trainees.Count() / pageSize),
                Items = context.Trainees.Skip((page - 1) * pageSize).Take(pageSize).ToList()
            };

            return View("Index", traineeVM);
        }

        [HttpPost]
        public IActionResult Search(string searchString, string propertyToSearch)
        {
            List<Trainee> filteredTrainees;
            SearchVM<Trainee> traineeSearchVM;

            switch (propertyToSearch)
            {
                case "address":
                    filteredTrainees = context.Trainees.Where(tr => tr.Address.Contains(searchString)).ToList();
                    break;
                case "grade":
                    decimal grade;
                    Decimal.TryParse(searchString, out grade);
                    filteredTrainees = context.Trainees.Where(tr => tr.Grade == grade).ToList();
                    break;
                default: // Otherwise, search by name.
                    filteredTrainees = context.Trainees.Where(tr => tr.Name.Contains(searchString)).ToList();
                    break;
            }

            traineeSearchVM = new SearchVM<Trainee>()
            {
                SearchString = searchString,
                SearchProperty = propertyToSearch,
                Items = filteredTrainees
            };

            return View("Search", traineeSearchVM);
        }

        public IActionResult Details(int id)
        {
            var traineeVM = context.Trainees.Where(tr => tr.Id == id)
                .Select(tr => new TraineeDetailsVM
                {
                    TraineeId = tr.Id,
                    TraineeName = tr.Name,
                    TraineeAddress = tr.Address,
                    TraineeGrade = tr.Grade,
                    TraineeImageUrl = tr.ImageUrl,
                    DepartmentId = tr.DepartmentId,
                    DepartmentName = tr.Department.Name,
                    CourseResults = context.CourseResults
                        .Where(crs => crs.TraineeId == tr.Id)
                        .Select(crs => new StudentWithCourseDegreeVM
                        {
                            CrsName = crs.Course.Name,
                            Degree = crs.Degree,
                            IsPassed = crs.Degree >= crs.Course.MinDegree
                        }).ToList()
                }
                ).FirstOrDefault();

            return View("Details", traineeVM);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var addTraineeVM = new TraineeWithDepartmentsVM()
            {
                Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList()
            };
            return View("Add", addTraineeVM);
        }

        [HttpPost]
        public async Task<IActionResult> Add(TraineeWithDepartmentsVM traineeVM)
        {
            if (!ModelState.IsValid)
            {
                traineeVM.Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList();

                return View("Add", traineeVM);
            }

            var trainee = new Trainee()
            {
                Name = traineeVM.TraineeName,
                Address = traineeVM.TraineeAddress,
                Grade = traineeVM.TraineeGrade,
                DepartmentId = traineeVM.DepartmentId,
                ImageUrl = await UploadImage(traineeVM.imgFile) // Upload the img and get its path, if error ocurred returns Empty string.
            };

            context.Trainees.Add(trainee);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var trainee = context.Trainees.FirstOrDefault(ins => ins.Id == id);

            var editTraineeVM = new TraineeWithDepartmentsVM()
            {
                TraineeId = trainee.Id,
                TraineeName = trainee.Name,
                TraineeAddress = trainee.Address,
                TraineeGrade = trainee.Grade,
                TraineeImageUrl = trainee.ImageUrl,
                DepartmentId = trainee.DepartmentId,
                Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList()
            };

            return View("Edit", editTraineeVM);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(TraineeWithDepartmentsVM editTraineeVM)
        {
            if (!ModelState.IsValid)
            {
                editTraineeVM.Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList();

                return View("Edit", editTraineeVM);
            }


            var trainee = context.Trainees.FirstOrDefault(ins => ins.Id == editTraineeVM.TraineeId);

            if (editTraineeVM.imgFile != null) // If the user uploaded a new image, remove the old one.
            {
                RemoveImage(trainee.ImageUrl);
            }

            trainee.Name = editTraineeVM.TraineeName;
            trainee.Address = editTraineeVM.TraineeAddress;
            trainee.Grade = editTraineeVM.TraineeGrade ?? trainee.Grade;
            trainee.DepartmentId = editTraineeVM.DepartmentId;
            trainee.ImageUrl = await UploadImage(editTraineeVM.imgFile); // Upload the img and get its path, if error ocurred returns Empty string.

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpDelete]

labs/Server_Side/MVC/Day_7-8/Institute/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Institute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Institute.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Institute</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Institute - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

labs/Server_Side/MVC/Day_7-8/Institute/Views/Shared/_NavBar.cshtml
<!--NavBar Partial View-->

<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="/">Institute</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            Menu
            <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ms-auto py-4 py-lg-0">
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Home" asp-action="Index">
                        <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "activeNav" : "")">
                            <i class="bi bi-house-door-fill"></i>
                            Home
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4 " asp-area="" asp-controller="Instructor" asp-action="Index">
                        <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Instructor" ? "activeNav" : "")">
                            <i class="bi bi-person-badge-fill"></i>
                            Instructors
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Trainee" asp-action="Index">
                        <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Trainee" ? "activeNav" : "")">
                            <i class="bi bi-person-fill"></i>
                            Trainees
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Department" asp-action="Index">
                        <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Department" ? "activeNav" : "")">
                            <i class="bi bi-building-fill"></i>
                            Departments
                        </span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Course" asp-action="Index">
                        <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Course" ? "activeNav" : "")">
                            <i class="bi bi-journal-bookmark-fill"></i>
                            Courses
                        </span>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

labs/Server_Side/MVC/Day_7-8/Institute/Views/Shared/_NewLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Institute</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Institute.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/NewLayout.style.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-buildings-fill"></i>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">
                                <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "activeNav" : "")" >
                                    <i class="bi bi-house-door-fill"></i>
                                    Home
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Instructor" asp-action="Index">
                                <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Instructor" ? "activeNav" : "")">
                                    <i class="bi bi-person-badge-fill"></i>
                                    Instructors
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Trainee" asp-action="Index">
                                <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Trainee" ? "activeNav" : "")">
                                    <i class="bi bi-person-fill"></i>
                                    Trainees
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Department" asp-action="Index">
                                <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Department" ? "activeNav" : "")">
                                    <i class="bi bi-building-fill"></i>
                                    Departments
                                </span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark " asp-area="" asp-controller="Course" asp-action="Index">
                                <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Course" ? "activeNav" : "")">
                                    <i class="bi bi-journal-bookmark-fill"></i>
                                    Courses
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Institute - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

labs/Server_Side/MVC/Day_7-8/Institute/Views/Shared/_TempLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Institute</title>
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <!-- Navigation-->
    <partial name="_NavBar" />

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>@ViewData["HeaderTitle"]</h1>
                        <span class="subheading">@ViewData["HeaderSubTitle"]</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5 mb-5">
        @* @RenderBody() *@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://x.com/ku18m1">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/ku18m">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/ku18m">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Institute - 2024</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> *@
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>

    <!--JQuery local libraries-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--Views Scripst-->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>