labs/Server_Side/MVC/Day_6/Institute/Controllers/CourseController.cs
using Institute.Models;
using Institute.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Institute.Controllers
{
    public class CourseController : Controller
    {
        private readonly InstituteContext context = new();
        public IActionResult ShowCourseResult(int id)
        {
            var courseResults = context.CourseResults
                .Where(crs => crs.CourseId == id)
                .Select
                (
                    crsresult => new StudentWithCourseDegreeVM()
                    {
                        TraineeName = crsresult.Trainee.Name,
                        Degree = crsresult.Degree,
                        IsPassed = crsresult.Degree >= crsresult.Course.MinDegree
                    }
                ).ToList();

            if (courseResults.Count == 0)
            {
                return NotFound();
            }

            var courseResultsVM = new CourseResultsVM()
            {
                CourseName = context.Courses.Find(id).Name,
                CourseResults = courseResults
            };

            return View("ShowCourseResult", courseResultsVM);
        }

        public IActionResult Index(int page = 1)
        {
            int pageSize = 5;
            var coursesVM = new PaginationVM<Course>()
            {
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling((double)context.Courses.Count() / pageSize),
                Items = context.Courses.Skip((page - 1) * pageSize).Take(pageSize).ToList()
            };

            return View("Index", coursesVM);
        }

        [HttpPost]
        public IActionResult Search(SearchVM<Course> searchVM)
        {
            List<Course> filteredCourses;
            SearchVM<Course> courseSearchVM;

            switch (searchVM.SearchProperty)
            {
                case "hours":
                    int hours;
                    int.TryParse(searchVM.SearchString, out hours);
                    filteredCourses = context.Courses.Where(crs => crs.Hours == hours).ToList();
                    break;
                case "degree":
                    int degree;
                    int.TryParse(searchVM.SearchString, out degree);
                    filteredCourses = context.Courses.Where(crs => crs.Degree == degree).ToList();
                    break;
                case "minDegree":
                    int minDegree;
                    int.TryParse(searchVM.SearchString, out minDegree);
                    filteredCourses = context.Courses.Where(crs => crs.MinDegree == minDegree).ToList();
                    break;
                default: // Otherwise, search by name.
                    filteredCourses = context.Courses.Where(tr => tr.Name.Contains(searchVM.SearchString)).ToList();
                    break;
            }

            searchVM.Items = filteredCourses;

            return View("Search", searchVM);
        }

        public IActionResult Details(int id)
        {
            var courseVM = context.Courses.Where(crs => crs.Id == id)
                .Select(crs => new CourseDetailsVM
                {
                    CourseId = crs.Id,
                    CourseName = crs.Name,
                    CourseDegree = crs.Degree,
                    CourseHours = crs.Hours,
                    CourseMinDegree = crs.MinDegree,
                    DepartmentId = crs.DepartmentId,
                    DepartmentName = crs.Department.Name,
                    Instructors = crs.Instructors.ToList(),
                    CourseResults = context.CourseResults
                        .Where(crs => crs.CourseId == crs.Id)
                        .Select(crslt => new StudentWithCourseDegreeVM
                        {
                            TraineeName = crslt.Trainee.Name,
                            Degree = crslt.Degree,
                            IsPassed = crslt.Degree >= crslt.Course.MinDegree
                        }).ToList()
                }
                ).FirstOrDefault();

            return View("Details", courseVM);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var addCourseVM = new CourseWithDepartmentsVM()
            {
                Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList()
            };
            return View("Add", addCourseVM);
        }

        [HttpPost]
        public IActionResult Add(CourseWithDepartmentsVM courseVM)
        {
            if (!ModelState.IsValid)
            {
                courseVM.Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList();

                return View("Add", courseVM);
            }

            var course = new Course()
            {
                Name = courseVM.CourseName,
                Hours = courseVM.CourseHours,
                Degree = courseVM.CourseDegree,
                MinDegree = courseVM.CourseMinDegree,
                DepartmentId = courseVM.DepartmentId,
            };

            context.Courses.Add(course);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var course = context.Courses.Find(id);

            var editCourseVM = new CourseWithDepartmentsVM()
            {
                CourseId = course.Id,
                CourseName = course.Name,
                CourseHours = course.Hours,
                CourseDegree = course.Degree,
                CourseMinDegree = course.MinDegree,
                DepartmentId = course.DepartmentId,
                Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList()
            };

            return View("Edit", editCourseVM);
        }

        [HttpPost]
        public IActionResult Edit(CourseWithDepartmentsVM editCourseVM)
        {
            if (!ModelState.IsValid)
            {
                editCourseVM.Departments = context.Departments.Select(dept => new SelectListItem
                {
                    Value = dept.Id.ToString(),
                    Text = dept.Name
                }).ToList();

                return View("Edit", editCourseVM);
            }

            var course = context.Courses.Find(editCourseVM.CourseId);

            course.Name = editCourseVM.CourseName;
            course.Hours = editCourseVM.CourseHours;
            course.Degree = editCourseVM.CourseDegree;
            course.MinDegree = editCourseVM.CourseMinDegree;
            course.DepartmentId = editCourseVM.DepartmentId;

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            try
            {
                var course = context.Courses.Find(id);
                if (course == null)
                {
                    return StatusCode(404, new { message = "Course not found." });
                }
                context.Courses.Remove(course);
                context.SaveChanges();
                return StatusCode(201, new { message = "Course successfully removed." });
            }
            catch
            {
                return StatusCode(500, $"An error occured while removing the Course.");
            }
        }

        public IActionResult ValidateMinDegree(int courseMinDegree, int courseDegree)
        {
            if (courseMinDegree > courseDegree)
            {
                return Json("Course Degree is lower than the minimum degree.");
            }
            return Json(true);
        }

        public IActionResult ValidateHours(int courseHours)
        {
            if (courseHours % 3 != 0)
            {
                return Json("The course hours must be divisible by 3.");
            }
            return Json(true);
        }
    }
}

labs/Server_Side/MVC/Day_6/Institute/Controllers/DepartmentController.cs
using Institute.Models;
using Institute.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Institute.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly InstituteContext context = new();
        public IActionResult Index(int page = 1)
        {
            int pageSize = 5;
            var departmentVM = new PaginationVM<Department>()
            {
                CurrentPage = page,
                TotalPages = (int)Math.Ceiling((double)context.Departments.Count() / pageSize),
                Items = context.Departments.Skip((page - 1) * pageSize).Take(pageSize).ToList()
            };

            return View("Index", departmentVM);
        }

        [HttpPost]
        public IActionResult Search(string searchString, string propertyToSearch)
        {
            List<Department> filteredDepartments;
            SearchVM<Department> departmentSearchVM;

            switch (propertyToSearch)
            {
                case "manager":
                    filteredDepartments = context.Departments.Where(dept => dept.Manager.Contains(searchString)).ToList();
                    break;
                default: // Otherwise, search by name.
                    filteredDepartments = context.Departments.Where(dept => dept.Name.Contains(searchString)).ToList();
                    break;
            }

            departmentSearchVM = new SearchVM<Department>()
            {
                SearchString = searchString,
                SearchProperty = propertyToSearch,
                Items = filteredDepartments
            };

            return View("Search", departmentSearchVM);
        }

        public IActionResult Details(int id)
        {
            var departmentVM = context.Departments.Where(tr => tr.Id == id)
                .Select(dept => new DepartmentDetailsVM
                {
                    DepartmentId = dept.Id,
                    DepartmentName = dept.Name,
                    DepartmentManager = dept.Manager,
                    Instructors = dept.Instructors.ToList(),
                    Courses = dept.Courses.ToList()
                }
                ).FirstOrDefault();

            return View("Details", departmentVM);
        }

        [HttpGet]
        public IActionResult Add()
        {
            var addDepartmentVM = new DepartmenModifytVM();

            return View("Add", addDepartmentVM);
        }

        [HttpPost]
        public IActionResult Add(DepartmenModifytVM departmentVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Add", departmentVM);
            }

            var department = new Department()
            {
                Name = departmentVM.DepartmentName,
                Manager = departmentVM.DepartmentManager
            };

            context.Departments.Add(department);
            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var department = context.Departments.Find(id);

            var editDepartmentVM = new DepartmenModifytVM()
            {
                DepartmentId = department.Id,
                DepartmentName = department.Name,
                DepartmentManager = department.Manager
            };

            return View("Edit", editDepartmentVM);
        }

        [HttpPost]
        public IActionResult Edit(DepartmenModifytVM editDepartmentVM)
        {
            if (!ModelState.IsValid)
            {
                return View("Edit", editDepartmentVM);
            }

            var department = context.Departments.Find(editDepartmentVM.DepartmentId);

            department.Name = editDepartmentVM.DepartmentName;
            department.Manager = editDepartmentVM.DepartmentManager;

            context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            try
            {
                var department = context.Departments.Find(id);
                if (department == null)
                {
                    return StatusCode(404, new { message = "Department not found." });
                }
                context.Departments.Remove(department);
                context.SaveChanges();
                return StatusCode(201, new { message = "Department successfully removed." });
            }
            catch
            {
                return StatusCode(500, $"An error occured while removing the Department.");
            }
        }
    }
}

labs/Server_Side/MVC/Day_6/Institute/Views/Shared/_TempLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Institute</title>
    <link rel="icon" type="image/x-icon" href="/assets/favicon.ico" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="/css/styles.css" rel="stylesheet" />
    <!--Bootstrap Icons-->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="/">Institute</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto py-4 py-lg-0">
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Home" asp-action="Index">
                            <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Home" ? "activeNav" : "")">
                                <i class="bi bi-house-door-fill"></i>
                                Home
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4 " asp-area="" asp-controller="Instructor" asp-action="Index">
                            <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Instructor" ? "activeNav" : "")">
                                <i class="bi bi-person-badge-fill"></i>
                                Instructors
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Trainee" asp-action="Index">
                            <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Trainee" ? "activeNav" : "")">
                                <i class="bi bi-person-fill"></i>
                                Trainees
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Department" asp-action="Index">
                            <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Department" ? "activeNav" : "")">
                                <i class="bi bi-building-fill"></i>
                                Departments
                            </span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link px-lg-3 py-3 py-lg-4" asp-area="" asp-controller="Course" asp-action="Index">
                            <span class="@(ViewContext.RouteData.Values["controller"].ToString() == "Course" ? "activeNav" : "")">
                                <i class="bi bi-journal-bookmark-fill"></i>
                                Courses
                            </span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Page Header-->
    <header class="masthead" style="background-image: url('/assets/img/home-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <div class="site-heading">
                        <h1>@ViewData["HeaderTitle"]</h1>
                        <span class="subheading">@ViewData["HeaderSubTitle"]</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content-->
    <div class="container px-4 px-lg-5 mb-5">
        @* @RenderBody() *@
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Footer-->
    <footer class="border-top">
        <div class="container px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-10 col-lg-8 col-xl-7">
                    <ul class="list-inline text-center">
                        <li class="list-inline-item">
                            <a href="https://x.com/ku18m1">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://www.facebook.com/ku18m">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li class="list-inline-item">
                            <a href="https://github.com/ku18m">
                                <span class="fa-stack fa-lg">
                                    <i class="fas fa-circle fa-stack-2x"></i>
                                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <div class="small text-center text-muted fst-italic">Copyright &copy; Your Website 2023</div>
                </div>
            </div>
        </div>
    </footer>
    <!-- Bootstrap core JS-->
    @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script> *@
    <!-- Core theme JS-->
    <script src="/js/scripts.js"></script>

    <!--JQuery local libraries-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--Views Scripst-->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>